# Generated by Django 5.2 on 2026-01-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewithstyle', '0002_contactmessage_testimonial_vehicle_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
