# Generated by Django 5.2 on 2026-07-26 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewithstyle', '0003_vehicle_price_per_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('promotion_type', models.CharField(choices=[('announcement', 'Announcement'), ('discount', 'Discount'), ('special_event', 'Special Event'), ('global_campaign', 'Global Campaign')], default='announcement', max_length=24)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label shown above the promotion, for example Eid Offer or Airport Week.', max_length=80)),
                ('summary', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, help_text='Optional campaign poster or event artwork shown on the website.', null=True, upload_to='promotions/')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, help_text='Optional percentage discount.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional fixed discount amount in PKR.', max_digits=10, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('audience_region', models.CharField(default='Worldwide', help_text='Examples: Worldwide, Islamabad, GCC travelers, UK customers.', max_length=80)),
                ('cta_label', models.CharField(default='Book now', max_length=40)),
                ('cta_url', models.CharField(default='/book', help_text='Use a site path such as /book or a full external URL.', max_length=255)),
                ('terms', models.CharField(blank=True, max_length=240)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured promotions are given stronger visual priority on the homepage.')),
                ('show_in_announcement_bar', models.BooleanField(default=True, help_text='Show this promotion in compact announcement placements.')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.ForeignKey(blank=True, help_text='Leave empty if this applies to the whole fleet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='drivewithstyle.vehicle')),
            ],
            options={
                'verbose_name': 'Promotion / Announcement',
                'verbose_name_plural': 'Promotions & Announcements',
                'ordering': ['priority', '-is_featured', '-created_at'],
            },
        ),
    ]
