# Generated by Django 5.2 on 2026-07-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewithstyle', '0004_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=140)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='drivewithstyle.vehicle')),
            ],
            options={
                'verbose_name': 'Fleet Gallery Image',
                'verbose_name_plural': 'Fleet Gallery Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
